---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages (python3-pip and software-properties-common)
  apt:
    name:
      - python3-pip
      - software-properties-common
    state: present


- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    update_cache: yes

- name: Install Ansible
  apt:
    name: ansible
    state: present

- name: Copy CAC-Ansible directory to access node
  copy:
    src: "{{ playbook_dir }}"
    dest: /home/{{ ansible_user }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
    remote_src: no

- name: install kubectl and helm on access node
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh


  
