apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskops-testing
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ShehabFahmy/test.git
    targetRevision: HEAD
    path: overlays/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true