apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskops
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmd-Sadka/FlaskOps-on-k8s.git
    targetRevision: HEAD
    path: charts/FlaskOps
  destination:
    server: https://kubernetes.default.svc
    namespace: flaskops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true