apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmd-Sadka/FlaskOps-on-k8s.git
    targetRevision: HEAD
    path: charts/kube-prometheus-stack
    helm:
      valueFiles:
        - monitoring.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true