apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmd-Sadka/FlaskOps-on-k8s.git
    targetRevision: HEAD
    path: charts/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true