apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/flaskapp

patches:
  - target:
      kind: Service
      name: flaskapp-svc
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
  - target:
      kind: Deployment
      name: flaskapp-depl
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
